# .air.toml
# See https://github.com/cosmtrek/air#configuration for latest format

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/web"
  bin = "tmp/main.exe"
  full_bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  stop_on_error = true


[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
